package com.renthouse.enums;

public enum MessageType {
    TERMINATION_REQUEST,
    TERMINATION_RESPONSE,
    FORCE_TERMINATION_NOTICE,
    ADMIN_NOTIFICATION,
    CONTRACT_APPROVAL_NOTICE,
    CONTRACT_REJECTION_NOTICE,
    HOUSE_PENDING_STAFF_REVIEW,
    HOUSE_REVIEW_RESULT,
    CONTRACT_PENDING_STAFF_SIGNING,
    CONTRACT_PENDING_ADMIN_APPROVAL,
    CONTRACT_SIGNING_NOTICE,
    TERMINATION_PENDING_STAFF_REVIEW,
    USER_CHAT
}
