-- ==========================================
-- easy_rent schema v3 (unified accounts)
-- ==========================================

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    account_type VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT 'USER/STAFF/ADMIN',
    real_name VARCHAR(50) NULL,
    display_name VARCHAR(80) NULL,
    phone VARCHAR(20) NULL,
    email VARCHAR(100) NULL,
    id_card VARCHAR(20) NULL,
    avatar VARCHAR(255) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    can_publish TINYINT(1) NOT NULL DEFAULT 1,
    can_rent TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_accounts_username (username),
    INDEX idx_accounts_type (account_type),
    INDEX idx_accounts_enabled (enabled),
    INDEX idx_accounts_phone (phone),
    INDEX idx_accounts_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Unified accounts for user/staff/admin';

CREATE TABLE IF NOT EXISTS houses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    address VARCHAR(255) NOT NULL,
    district VARCHAR(100) NULL,
    house_type VARCHAR(50) NOT NULL,
    area DECIMAL(10,2) NULL,
    floor INT NULL,
    rent_price DECIMAL(10,2) NOT NULL,
    deposit DECIMAL(10,2) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING_STAFF_REVIEW'
        COMMENT 'PENDING_STAFF_REVIEW/AVAILABLE/PENDING/RENTED/OFFLINE',
    description TEXT NULL,
    images MEDIUMTEXT NULL COMMENT 'Pipe-separated image URLs',
    facilities TEXT NULL,
    view_count INT DEFAULT 0,
    assigned_staff_id BIGINT NULL COMMENT 'accounts.id',
    review_comment TEXT NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES accounts(id) ON DELETE CASCADE,
    INDEX idx_houses_owner (owner_id),
    INDEX idx_houses_status (status),
    INDEX idx_houses_district (district),
    INDEX idx_houses_rent (rent_price),
    INDEX idx_houses_staff (assigned_staff_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='House listings';

CREATE TABLE IF NOT EXISTS contracts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    house_id BIGINT NOT NULL,
    landlord_id BIGINT NOT NULL COMMENT 'accounts.id',
    tenant_id BIGINT NOT NULL COMMENT 'accounts.id',
    rent_price DECIMAL(10,2) NOT NULL,
    deposit DECIMAL(10,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING_LANDLORD_APPROVAL'
        COMMENT 'PENDING_LANDLORD_APPROVAL/PENDING_STAFF_SIGNING/PENDING_ADMIN_APPROVAL/ACTIVE/EXPIRED/TERMINATED/REJECTED/TERMINATION_PENDING/TERMINATION_PENDING_COUNTERPARTY/TERMINATION_PENDING_STAFF_REVIEW/TERMINATION_FORCE_PENDING_JOINT_REVIEW',
    signed_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    notes TEXT NULL,
    assigned_staff_id BIGINT NULL COMMENT 'accounts.id',
    signed_contract_url VARCHAR(500) NULL,
    signed_contract_name VARCHAR(255) NULL,
    signed_contract_uploaded_at DATETIME NULL,
    signed_contract_uploaded_by BIGINT NULL COMMENT 'accounts.id',
    landlord_termination_reject_count INT DEFAULT 0,
    tenant_termination_reject_count INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (house_id) REFERENCES houses(id) ON DELETE CASCADE,
    FOREIGN KEY (landlord_id) REFERENCES accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES accounts(id) ON DELETE CASCADE,
    INDEX idx_contracts_house (house_id),
    INDEX idx_contracts_landlord (landlord_id),
    INDEX idx_contracts_tenant (tenant_id),
    INDEX idx_contracts_status (status),
    INDEX idx_contracts_staff (assigned_staff_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Rental contracts';

CREATE TABLE IF NOT EXISTS termination_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL COMMENT 'accounts.id',
    responder_id BIGINT NULL COMMENT 'accounts.id',
    review_staff_id BIGINT NULL COMMENT 'accounts.id',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED/FORCE_TERMINATED',
    reason TEXT NULL,
    force_reason TEXT NULL,
    force_request TINYINT(1) DEFAULT 0,
    evidence_urls TEXT NULL COMMENT 'Comma-separated evidence URLs',
    counterparty_comment TEXT NULL,
    staff_approved TINYINT(1) DEFAULT 0,
    admin_approved TINYINT(1) DEFAULT 0,
    staff_follow_up_plan TEXT NULL,
    admin_decision_comment TEXT NULL,
    admin_notified TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (responder_id) REFERENCES accounts(id) ON DELETE CASCADE,
    INDEX idx_termination_contract (contract_id),
    INDEX idx_termination_status (status),
    INDEX idx_termination_staff (review_staff_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Contract termination requests';

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sender_id BIGINT NULL COMMENT 'USER sender accounts.id',
    receiver_id BIGINT NULL COMMENT 'USER receiver accounts.id',
    sender_operator_id BIGINT NULL COMMENT 'STAFF/ADMIN sender accounts.id',
    receiver_operator_id BIGINT NULL COMMENT 'STAFF/ADMIN receiver accounts.id',
    sender_operator_name VARCHAR(80) NULL,
    receiver_operator_name VARCHAR(80) NULL,
    title VARCHAR(200) NULL,
    content TEXT NULL,
    message_type VARCHAR(50) NULL,
    status VARCHAR(20) DEFAULT 'UNREAD' COMMENT 'UNREAD/READ/PENDING/ACCEPT/REJECT/ARCHIVED',
    related_contract_id BIGINT NULL,
    related_house_id BIGINT NULL,
    related_request_id BIGINT NULL,
    require_action TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    read_at DATETIME NULL,
    archived_by_user_ids VARCHAR(500) NULL COMMENT 'Archived USER account ids',
    FOREIGN KEY (sender_id) REFERENCES accounts(id) ON DELETE SET NULL,
    FOREIGN KEY (receiver_id) REFERENCES accounts(id) ON DELETE SET NULL,
    INDEX idx_messages_sender (sender_id),
    INDEX idx_messages_receiver (receiver_id),
    INDEX idx_messages_sender_operator (sender_operator_id),
    INDEX idx_messages_receiver_operator (receiver_operator_id),
    INDEX idx_messages_status (status),
    INDEX idx_messages_contract (related_contract_id),
    INDEX idx_messages_house (related_house_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Message center';
